name: serverless build

on:
  workflow_call:
    outputs:
      build_tag:
        description: The build_tag for the code that has been built and published
        value: ${{ jobs.build.outputs.build_tag }}

env:
  node_version: 18
  service_name: dm-tools-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: "npm"

      - name: Install / restore dependencies
        run: npm ci